datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./db"
  production:
    username: ${username}
    password: ${password}
    url: ${JDBC_DATABASE_URL}

ebean:
  development:
    migration:
      run: true
  production:
    ddl:
      run: true
      generate: true
    # migration:
    #  run: true
